recipes:
    mac_os_x:
        - applications::gnu-tar
        - osxdefaults::disable_disk_image_verification
        - osxdefaults::disable_front_row
        - osxdefaults::disable_gatekeeper
        - osxdefaults::do_not_show_dashboard_as_a_space
        - osxdefaults::do_not_show_dashboard_as_a_space
        - osxdefaults::dock_automatically_hide_and_show_the_dock
        - osxdefaults::finder_search_the_current_folder_by_default
        - osxdefaults::menu_add_battery_percentage
        - osxdefaults::set_computer_name
        - osxdefaults::tap_to_click
        - osxdefaults::avoid_creating_ds_store_files_on_network_volumes
attributes:
    osxdefaults:
        computername: gajeel
        loginmessage: Property of Gabriel Poca
