recipes:
    global:
        - applications::create_var_chef_cache
    mac_os_x:
        - homebrewalt::default
        - nodejs::default
attributes:
    homebrewalt:
        apps:
            - cmus
            - git
            - gnupg
            - imagemagick
            - irssi
            - mplayer
            - nmap
            - tmux
            - wget
            - postgres
            - macvim
                --override-system-vim
            - zsh
    nodejs:
        apps:
            - phonegap
            - cordova
            - grunt
            - grunt-cli
